#!/usr/bin/env bash

# Make sure the user is not root. so we can get the user id.
user_id=$UID
if [[ "$user_id" == "0" ]] ; then
	echo "Do not run as root. Packagetastic will ask for name/password itself. Exiting ..."
	exit
fi

# Run the program as root, but
# pass in the current distro name and user id
sudo python packagetastic.py $@ `lsb_release -is` $UID


